### ISSUE TITLE
9DOF

### ISSUE THREAD

**Issue by Darthpbal** [Darthpbal/eclipse-ASUPayload#18]
- [x] design and document subcircuit. Add to master.
  - [ ] using relevant subcircuit, demo sensor alone, verify accuracy
  - [ ] Demo operating next to other sensors while logging to sd card compatible with desired logging speed, reverify accuracy.
  - [ ] Implement code into the master program on a unique git branch, retest and reverify, then merge into the master project branch.

**Comment by Darthpbal** [comment]
product [page](https://www.adafruit.com/product/3463) for the 9dof for use in the payload

**Comment by bmpina** [comment]
ready for integration

**Comment by bmpina** [comment]
Processing software does not work, look more into after launch

**Comment by bmpina** [comment]
integrated into system
