### ISSUE TITLE
Humidity DHT22

### ISSUE THREAD

**Issue by Darthpbal** [Darthpbal/eclipse-ASUPayload#19]
- [x] design and document subcircuit. Add to master.
  - [ ] using relevant subcircuit, demo sensor alone, verify accuracy
  - [ ] Demo operating next to other sensors while logging to sd card compatible with desired logging speed, reverify accuracy.
  - [ ] Implement code into the master program on a unique git branch, retest and reverify, then merge into the master project branch.

**Comment by Darthpbal** [comment]
datasheet [page](https://cdn-shop.adafruit.com/datasheets/DHT22.pdf)

hookup guide [page](https://learn.adafruit.com/dht)

**Comment by bmpina** [comment]
I tested 2 of these sensors. 
#1 seems to be working fine.
#2 is giving off slightly skewed values and I believe that is due to a bad wire connection. I need a soldering Iron to fix the wiring.

**Comment by bmpina** [comment]
Tested the LM35 Temp sensor we found in the lab. It works so it can be used as a backup

**Comment by bmpina** [comment]
Tested the DS18B20 Temp sensor we found in the lab. It works so it can be used as a backup.

**Comment by bmpina** [comment]
The LM35 temp sensor we found in the lab is an outdated sensor that does not work well for arduinos.

**Comment by bmpina** [comment]
Tested the HIH-4030 humidity sensor we found in the lab. The values are a bit high and it could be due to the fact that the sensor is very sensitive to damage/ESD and it was stored improperly. I recommend we stick to the DHT22 for humidity measurements.

**Comment by bmpina** [comment]
integrated into system
